### ISSUE TITLE
Update Application State Architecture

### ISSUE THREAD

**Issue by tjmareng** [bsiever/microbit-usb-grapher#23]
## Story
As an Developer,
I would like to update the architecture of the application to better accommodate the React state,
So that the app is intuitive to develop upon and contains best practices 

## Additional Context
- Components contain state (which should not be the case)
- The App container contains graph state which should be moved to the Graph container

## Planning Details
Graph state related to the graph (Title, Micro:bit Data, Styling, etc) should be moved the the graph container. Additionally, functions related to the graphs should be moved to the Graph container.

### Tasks
- [ ] Move graph state to Graph container (src/containers/graph/index.js)
     - [ ] Micro:bit Data
     - [ ] Graph Title
     - [ ] Styling
- [ ] Remove graph related state from the Home container (src/containers/Home/index.js)
